apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      env: deploy
  template: 
    metadata: 
      labels: 
        env: deploy
      name: myweb-pod
    spec: 
      containers: 
      - image: ashwani2399/webserver:v1
        name: myweb-pod
        volumeMounts:
        - name: myweb-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: myweb-persistent-storage
        persistentVolumeClaim:
