apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      env: deployment
  template: 
    metadata: 
      labels: 
        env: deployment
      name: myweb-pod
    spec: 
      containers: 
      - image: ashwani2399/webserver:v1
        name: myweb-pod
        
